# Generated by Django 3.2.16 on 2023-03-25 06:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(default='', verbose_name='Слаг')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена товара')),
                ('discount_percent', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в процентах')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product', verbose_name='Изображение товара')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='Категория товара'),
        ),
    ]
